name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (optional)'
        required: false
        type: string
env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: yarn install

      - name: Set Git username
        run: |-
          git config --global user.name "Release It"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Publish default version
        if: ${{ inputs.version == '' }}
        run: yarn release-it --ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: ${{ inputs.version }}
        run: yarn release-it --ci -i ${{ inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
