name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write # to create release
  id-token: write # required for provenance and OIDC publish
  pull-requests: write # to create pull request

env:
  CI: true

jobs:
  release:
    if: github.repository == 'birchill/normal-jp'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v5
        if: ${{ steps.release.outputs.release_created }}

      - name: Install pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 24
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      # Temporary until setup-node action comes with npm version that contains
      # OIDC setup by default
      - name: update npm
        if: ${{ steps.release.outputs.release_created }}
        run: npm update -g npm

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install

      - run: npm publish --access public
        if: ${{ steps.release.outputs.release_created }}
