name: Automated tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
          cache: pnpm

      - name: Build
        run: |
          pnpm install
          pnpm build

      - name: Unit tests
        run: pnpm test

      - name: Knip
        run: pnpm knip
